### ISSUE TITLE
Unable to Build 2061 errors on LibLLVM

### ISSUE THREAD

**Issue by danwalmsley** [NETMF/llilum#105]
![image](https://cloud.githubusercontent.com/assets/4672627/11968466/6b0a8d2c-a904-11e5-9f89-53acb72ce32d.png)

Is there a missing step in the instructions?

I have built LLVM and not opened the zelig solution and right clicked solution, build solution..

**Comment by kail** [comment]
Can you verify that your registry has an entry in HKCU\Software\LLVM\3.7.0 called "SrcRoot"?

**Comment by danwalmsley** [comment]
Yes its there..

**Comment by danwalmsley** [comment]
![image](https://cloud.githubusercontent.com/assets/4672627/11987155/23549990-a9d2-11e5-8f01-49d04e1ae6b1.png)
points to this...

**Comment by kail** [comment]
This may seem silly, but can you clean the solution, and hit "CTRL + SHIFT + B" a few times to see if the error count goes down? Visual studio likes to act up at times. You can also try to build projects individually until one fails, and attempt to determine the cause.

If not, try cloning the repo to a different location and trying the steps again, without compiling LLVM (compiling LLVM is the long step, everything else should be quick). 

Unfortunately, I have never encountered the issue you are seeing, so I can't be of much help.

**Comment by smaillet-ms** [comment]
Did you run CMAKe manually or via the LLVM build script provided? It looks like the source headers and compiled binaries aren't sharing the same set of preprocessor conditionals so you get those mismatches.

**Comment by danwalmsley** [comment]
Hi, I'm just trying again... will see if the issue persists for me.

**Comment by danwalmsley** [comment]
right I started from scratch and now it works, thanks for help guys!
