### ISSUE TITLE
ReadByte test fails with fault

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#106]
REPRO: run MemoryStream test on K64F using 'mbed_simple_NET_K64F_Tester.FrontEndConfig'

**Comment by ckarenz** [comment]
Blocked by #114... this test allocates and frees quite a bit, so we're hitting OOM.

**Comment by lt72** [comment]
Just tested on K64F, and now passes. Likely fixed as a side effect or failure due to OOM.
