### ISSUE TITLE
Compiling VanillaWrite_Static_Ctor( ) and VanillaWrite() methods in MemoryStream tests fails to compile

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#107]
REPRO: compile with 'mbed_simple_NET_K64F_Tester.FrontEndConfig'

**Comment by ckarenz** [comment]
This is a phi operator where one value is undefined in all predecessors. Likely a glitch in the SSA transform.

**Comment by ckarenz** [comment]
Fixed by above change.
