### ISSUE TITLE
BinaryOperatorWithCarryOut is generated during FromImplicitToExplicitExceptions but is not handled

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#109]
REPRO: compile with 'REPRO: compile with 'mbed_simple_NET_K64F_Tester.FrontEndConfig'' after 
uncommenting usage StringBuilderTests in Test projects

Places that cause the bug are marked with this bug URL in the code

NOTE: there should be no reason at all not to allow generation of this operators and their translation to LLVM, as LLVM shoudl support emitting operators with flags (http://llvm.org/docs/LangRef.html#arithmetic-with-overflow-intrinsics). Please see to enable all binary operators that derive from AbstractBinaryOperator. 

NOTE: also see bug https://github.com/NETMF/llilum/issues/108! Enabling translating this operator cause the other bug to happen.

**Comment by ckarenz** [comment]
The referenced intrinsics are a bit different than the way we're emitting these operators, so we'll need to define a mechanism to associate the control operator with the arithmetic operator's second return value.

LLVM is also missing intrinsics for byte, so we'll need to inject calls to a helper method that we define.
