### ISSUE TITLE
Unable to start debugging Unexpected GDB output -target-select remote :3333

### ISSUE THREAD

**Issue by danwalmsley** [NETMF/llilum#117]
![image](https://cloud.githubusercontent.com/assets/4672627/12118768/2a07922c-b3c0-11e5-87c5-6fcbea9a6fc4.png)

I get this when trying to debug STM32 with ST Link.

**Comment by kail** [comment]
Hi Dan,  
This is an issue from OpenOCD not starting correctly. Please go to the Native project properties, Debugging tab, and check the following:  
- "Llilum Open Ocd" points to the correct location, and that OpenOCD was copied to that location
- **_(Most likely culprit)**_ "Llilum Open Ocd Args" should look like  `-f $(LlilumSDK)tools\openocd\scripts\interface\$(LlilumOpenOcdInterfaceCfg) -f $(LlilumSDK)tools\openocd\scripts\board\$(LlilumOpenOcdBoardCfg)` If you changed this, make sure you have the -f params in the right places
- "Llilum GDB Path" is correct and the file exists  

Lastly, just to be safe, right click on the Native project, Open Project Directory, and open the tmp_debug.bat file in there. If any of the paths look incorrect, or the files don't exist, make the appropriate changes in the debugging properties, delete the tmp_debug.bat file, and try to debug again.

**Comment by danwalmsley** [comment]
Hi, thanks I manually changes the Open OCD args to -f -f $(LlilumSDK)tools\openocd\scripts\interface\stlink-v2.cfg -f $(LlilumSDK) tools\openocd\scripts\target\stm32f4_stlink.cfg and had success, I couldn't see where those variables get defined.

That works now.
