### ISSUE TITLE
The application doesn't start

### ISSUE THREAD

**Issue by Palomino34** [NETMF/llilum#119]
Everything just worked fine before updating "VS update 1"
After installed "VS update 1", we can not debug. The error is shown as below

![debugfailed](https://cloud.githubusercontent.com/assets/15822304/12121553/e5534ca0-b3a3-11e5-9eca-85ab8d15a0b8.jpg)

After removed all GPIO objects then the application ran well. We knew it ran because we could debug.
Today we updated latest version which included fixing  "VS update 1", and the application does not start at all, although in main function just a while loop as below:

int a = 0;
while (true)
 {
           a++;
          if (a==0xFFFF) 
           a = 0;

```
} 
```

It is always point us to asm("bkpt");
please advice me?

**Comment by kail** [comment]
Sorry for the inconvenience, hopefully we can resolve this soon. What board are you currently working with? Have you changed the properties of the project to the correct board? Have you been able to debug the default SDK program? Lastly, if you had this working code before, have you done a clean and rebuild?

**Comment by Palomino34** [comment]
Enable MbedOSabstraction and Native in Configuration Manager before run CreateDropSDK, now it works.  I am not sure if these steps are necessary. But anyway, it is working. Thank a lot for fixing issue "VS update 1".

**Comment by kail** [comment]
Glad you have it working!
