### ISSUE TITLE
Compiling for mbed_simple_NET_K64F.FrontEndConfig causes exception during LLVM code gen

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#133]
see attached pic

REPRO: set FrontEnd config for 'mbed_simple_NET_K64F.FrontEndConfig' and build

![gep and int](https://cloud.githubusercontent.com/assets/8418852/12225429/61071470-b7bf-11e5-8def-52f7a6ff89d5.png)

**Comment by smaillet-ms** [comment]
no-repro here, try a clean build?

**Comment by lt72** [comment]
not repro-ing now :-) 
closing and let's see if it shows up

**Comment by lt72** [comment]
re-opening with new pro, and see attached email from Co

[Email Thread and Suggested Fix.pdf](https://github.com/NETMF/llilum/files/89542/Email.Thread.and.Suggested.Fix.pdf)
