### ISSUE TITLE
Wiki editing (?)

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#14]
Do you plan to enable public wiki editing?

There are a few things on the setup page that should be corrected and/or updated (minor fix for llilum-pr repository name, the GCC_BIN variable should be most likely set in the second cmd shell, Zelig.sln was renamed to LLILUM.sln; and there is startVS.cmd, LLVMIR is not under code transformations but CodeGenerator etc.)

**Comment by lt72** [comment]
I believe I enabled this, can you please try and re-open issue in case?
