### ISSUE TITLE
ArmProcessorEmulation missing referenced assemblies

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#15]
ArmProcessorEmulation project build fails due to missing referenced assemblies:
- JLinkInterface
- MacraigorOCDInterface
- RemoteDebugInterfaceConnector

They are supposed to be in `..\..\External\Binaries\JTAG\Debug`.

**Comment by lt72** [comment]
Fixed with commit [692fa72d5a60c47359b27e97d938c52469154a1b](https://github.com/NETMF/llilum/commit/692fa72d5a60c47359b27e97d938c52469154a1b)
