### ISSUE TITLE
SerialDevice.FromIdAsync() return type question

### ISSUE THREAD

**Issue by piwi1263** [NETMF/llilum#168]
Is the return type correct here for the SerialDevice.FromIdAsync() ?

![image](https://cloud.githubusercontent.com/assets/10466039/12734670/5e84f9e4-c942-11e5-8bfd-07d038345048.png)

Or should this match more to return just the Device as is done by the I2cDevice and the SpiDevice ?

**Comment by kail** [comment]
Hi,  

Sorry about the confusion there. The SerialDevice.FromIdAsync is the method that actually has the correct return type, while the ones for SpiDevice and I2cDevice are incorrect.

**Comment by piwi1263** [comment]
At least it is clear, but using the await for the SerialDevice.FindIdAsync() returns into a GetAwaiter not implemented/not found error.

**Comment by kail** [comment]
For now, please use .GetResults() on the IAsyncOperation. You can also use System.IO.Ports.SerialPort for serial communication. For all other peripherals, I would recommend using the classes in Microsoft.Llilum.Devices, as they are more lightweight than their UWP equivalents

**Comment by piwi1263** [comment]
Hi Mikhail,

thanks for answer, I'll give it a shot and see how far I come.

Cheers,

Peter.
