### ISSUE TITLE
Board STM32L152 missing

### ISSUE THREAD

**Issue by piwi1263** [NETMF/llilum#197]
The board and config projects are missing from the Zelig solution ->CompileTime->TargetModels and RunTime->DeviceModels->CortexM->Boards. Is there a reason for it ?

![zelig 1](https://cloud.githubusercontent.com/assets/10466039/13380733/fe5ee706-de49-11e5-8da1-70376b643cc9.JPG)

**Comment by lt72** [comment]
We added STM32L152 before all other STM32 boards. Now that we have the STM32F4 and F0, the STM32L152 is kind of redundant. No other reason.
