### ISSUE TITLE
Project compiling issues.

### ISSUE THREAD

**Issue by vgolovanov** [NETMF/llilum#233]
Hi.
i having problems with compiling LlilumSDK and Llilum project VSIX package.

1st issue, during compilation time, group of referenced libraries (NetmfCompatibilityComponentGroup) from ReferenceAssemblies file in  LlilumSDK not found. But commenting out or removing that section let compile the project.

2nd issue, when building VSIX package, getting error "The "FindInstalledExtension" task was not given a value for the required parameter "InstallableExtensionVersion". Microsoft.MIEngine.CoreRegisters.ARM"

Any help would be much appreciated.

Best regards,
Vyacheslav.

**Comment by nbsn2** [comment]
Just ignore those message.
Go find the .msi and  .vsix file, it's there.

**Comment by vgolovanov** [comment]
May be there is some switch to ignore that errors in Visual Studio.
But vsix file is not builded. Msi is builded, after i removed that section.

**Comment by vgolovanov** [comment]
Thank you for suggestion. Was looking VSIX file in wrong location.
