### ISSUE TITLE
What is the pronunciation?!

### ISSUE THREAD

**Issue by amirbalef** [NETMF/llilum#234]
Thank you for this outstanding project
What is the pronunciation of "llilum"?
What does the name stand for ?

**Comment by mbeddedFreak** [comment]
Hey Amir!

I think it is a combination of "L"ow + "L"evel + "IL"-based languages + "U"WP applications + micro ("U") + Cortex-"M" => LLILUM

Best regards.

**Comment by kail** [comment]
Bravo 👍 The name idea came from Microsoft's LLILC (pronounced "lilac"), and was modified to suggest that it targets MCUs. The pronunciation can be "lie-lum" or "li-li-um" (we use them interchangeably).
