### ISSUE TITLE
Error when building native application.

### ISSUE THREAD

**Issue by vgolovanov** [NETMF/llilum#25]
Hi.
I have a problem when compiling sample application.
During compiling process, zeling compiler stop working with message "Zelig Compiler has stop working".
From log messages, i see the error: 

"Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at Llvm.NET.LLVMNative.DisposeModule(LLVMModuleRef M)
     at Llvm.NET.Module.Dispose(Boolean disposing)
     at Llvm.NET.Module.Finalize()
"
Any help is appreciated. ) 
Thank you.

**Comment by lt72** [comment]
Thank you for reporting this, It is a known issue that does not break the code generation. It only happens at the end of the LLVM translation when we shut down the LLVM context. We have a race condition for which we shut down the LLVM context twice. At that point all code is already generated and you can move onto the next steps. 
We are fixing this issue with the next push.

**Comment by vgolovanov** [comment]
Thank you for your prompt reply. 
I have two more questions, not related to that problem. As i understand LLilum supports full .net framework, not a subset as NetMf ? Also i can't find implementations for SPI and I2C buses, is implement or not yet?

**Comment by kail** [comment]
Hi,
Sorry about the late reply! SPI and I2C are both ready to go, and will be made available in the very near future. As for .NET framework, since the target devices are even more resource constrained than the NETMF devices, Llilum will support libraries that are applicable to embedded and IoT development.
