### ISSUE TITLE
Zelig\Zelig\Test\mbed\SimpleSDK\Native\Native.vcxproj doesn't load

### ISSUE THREAD

**Issue by JoshCollinsMSFT** [NETMF/llilum#39]
When I load the Zelig solution, the Test\mbed\SDK\Native project doesn't load.  VS2015 doesn't give an error, however, loading it in VS2013 gives the following error:
'The imported project "D:\dev\git\llilum\Zelig\Zelig\Test\mbed\SimpleSDK\Native\Platforms\Llilum_LPC1768.props" was not found...'
I have verified this file doesn't exist (Platforms directory doesn't exist).

**Comment by lt72** [comment]
I disabled the project from being compiled and deployed by default in the solution.
the project s a LLILUM SDK project, and requires installing the VSIX for the LLILUM SDK to load
I will make a note in the docs!
