### ISSUE TITLE
Please, don't do such huge commits

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#41]
It is almost impossible to keep track of the changes and current state of the project when there is a single commit of thousands of changed files scattered all over the whole code base touching different and unrelated areas. Even if your current workflow is to publish once in a few months, please do keep separate commits, at least on feature or logical group level. Thank you in advance.

**Comment by lt72** [comment]
We are still working in the private repo, for a few days longer. We will be moving to work in the public repo very soon and toss the private repo, at which point there will be no need for huge commits.
