### ISSUE TITLE
"helpers.h" included twice

### ISSUE THREAD

**Issue by igvas** [NETMF/llilum#43]
in "llilum/VisualStudio/LlilumProjectType/LlilumApplication/LlilumApplication.ProjectTemplate/LlilumNative/Native.vcxproj" 
  tag  ClInclude Include="helpers.h"  meets twice. On llilum project creation causes an error.

**Comment by kail** [comment]
Thanks for reporting this! Issue has been fixed with the latest commit. Please let us know if you run into any other problems
