### ISSUE TITLE
DIBuilder Error

### ISSUE THREAD

**Issue by weixiongmei** [NETMF/llilum#52]
I just got the LLVM successfully builded, but still having problems when build the CreateSDKDrop.bat & Zelig.sln, there are two errors always appear.

error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’
error: 'llvm:DIBuilder::createSubroutineType' can't accept 3 params.

Please advise how to fix it, thank you~~

**Comment by rocuh** [comment]
I used this version http://llvm.org/releases/3.7.0/llvm-3.7.0.src.tar.xz 

I notice the llvm mirror on github has this:

```
 DISubroutineType *createSubroutineType(DITypeRefArray ParameterTypes,
                                           unsigned Flags = 0);
```

one in the archive has:

```
DISubroutineType *createSubroutineType(DIFile *File,
                                           DITypeRefArray ParameterTypes,
                                           unsigned Flags = 0);
```

**Comment by smaillet-ms** [comment]
Interesting the mirror has a different API signature... I'll have to look into that and see. I used the GitHub Mirror while 3.7.0 was still under development, but the version we use now should be the official files from the llvm.org site directly.

**Comment by smaillet-ms** [comment]
I just downloaded the source from LLVM Site  http://llvm.org/releases/3.7.0/llvm-3.7.0.src.tar.xz
and ran a full file by file diff against what we currently build with and it matches exactly, so we are building against the official release.

NOTE: The GitHub mirror will mirror the head of the development for whatever is the **next** release. (e.g. it does **not** contain the latest official released version but tracks active development of an unreleased version)

**Comment by weixiongmei** [comment]
thanks mr.roceh & mr.smaillet-ms, i just rebuild the LLVM 3.7.0, and those two issues have gone now, but still can't get the SDK builded. A new error appears,

\r [E:\llilum-dev\Zelig\Zelig\Test\mbed\SimpleSDK\Native\Native.vcxproj] C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB4018: System.Form at Exception: Index(Starting From Zero) Must greater than or equal to Zero, and smaller than the param list.

Having a lot of troubles when building this project... :(

**Comment by kail** [comment]
Please unload that project until you have installed the SDK. In order to create the SDK, please follow the steps here: https://github.com/NETMF/llilum/wiki/SDK-User-Guide (with the Native project unloaded). OR leave the project unloaded, and follow the steps here, for using Llilum without the SDK and using makefiles instead: https://github.com/NETMF/llilum/wiki/demo

**Comment by weixiongmei** [comment]
Hi Skobovm,

Still having the same problem even with the Native project unloaded in the Zelig.sln, any idea? thanks~~

**Comment by kail** [comment]
Where exactly are you in the setup process?

**Comment by weixiongmei** [comment]
Hi Skobovm,

Just got it working, thanks for you help, i have to unload and remove the Native project from the Zelig.sln, just unload it is not enough, thanks again~~~

**Comment by kail** [comment]
No problem! Good luck
