### ISSUE TITLE
HardwareProvider.Instance.InvalidPin Error

### ISSUE THREAD

**Issue by weixiongmei** [NETMF/llilum#53]
Sorry for opening so many issues here, but i really want to try the llilum, when i trying to do the debugging with the llilum managed code project, the visual studio will throws an ECall exception at the code
int invalidPin = HardwareProvider.Instance.InvalidPin;
in the BaseSerialStream.cs file

**Comment by weixiongmei** [comment]
how come Microsoft.Zelig.Runtime.MemoryManager.Instance.AvailableMemory is getting fewer and fewer?

**Comment by lt72** [comment]
Garbage collection is not implemented yet. We will push the first implementation to the repo in a matter of days. Watch for a commit that will read something like "Reference counting GC"
