### ISSUE TITLE
Local double and float array creation and assignment cannot be translated correctly to LLVM IR

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#55]
Enable test Simple_TestClass_init_init_a_05 to repro, and other tests that refer to this issue (#55)

**Comment by lt72** [comment]
please check that tests that are commented out currently work
e.g.: 
C:\src\forks\llilum\Zelig\Zelig\Test\RunTime\NETMF\mscorlib\arrays\ArraysSimpleTests.cs 
            //result |= Assert.CheckFailed( Simple_decl_decl_07_Test( ) ); // github issue #55

**Comment by ckarenz** [comment]
Will do, Monday.

On Jan 29, 2016, at 5:51 PM, Lorenzo Tessiore <notifications@github.com<mailto:notifications@github.com>> wrote:

please check that tests that are commented out currently work
e.g.:
C:\src\forks\llilum\Zelig\Zelig\Test\RunTime\NETMF\mscorlib\arrays\ArraysSimpleTests.cs
//result |= Assert.CheckFailed( Simple_decl_decl_07_Test( ) ); // github issue #55https://github.com/NETMF/llilum/issues/55

##

**Comment by lt72** [comment]
I actually already enabled all exceptions tests, included the ones that were commented out in other test suites
the ExceptionsTests suite will run first, then the others...  just need to see if they run  ;-)

**Comment by ckarenz** [comment]
Verified tests.
