### ISSUE TITLE
GPIO incorrectly checks for failure while creating DefaultPinProvider

### ISSUE THREAD

**Issue by ckarenz** [NETMF/llilum#56]
Found while enabling redundant null dead-stripping.  In GpioController.cs in the following code, provider can never be null:
            IGpioPinProvider provider = new DefaultPinProvider(pinNumber);

```
        if(provider == null)
        {
            pin.Dispose();
            pin = null;
            status = GpioOpenStatus.PinUnavailable;
            return false;
        }
```

We need to try/catch the creation of DefaultPinProvider and/or change the way we create the provider.

**Comment by lt72** [comment]
Mikhail, please take care of this issue with the same technique you are using for other similar types.

**Comment by kail** [comment]
Fixed this, and similar issues

**Comment by kail** [comment]
Fixed in https://github.com/NETMF/llilum/commit/84306453b8e91067490da8d25a8a24e08b55c02e
