### ISSUE TITLE
MbedOSAbstraction build fails with error MSB4018

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#70]
The latest solution build fails with `error MSB4018: The "VCMessage" task failed unexpectedly` in MbedOSAbstraction project. This is caused by an empty `PlatformToolset` variable which I think means that the project should be excluded from the build like it is done for Test/SDK/Native project (?)

**Comment by ZachNL** [comment]
Please try the latest update 0961081.  The MbedOSAbstraction project should not be built during the solution build.  It has now been disabled.  I can be built manually within the solution, but requires a new SDK to be created and installed first.

**Comment by cw2** [comment]
Fixed. Thanks :+1:
