### ISSUE TITLE
Q: Adding support for ARMv6-M ISA ?

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#71]
I am curious what would be (the high-level) steps to add support for ARMv6-M ISA (translated by LLVM) and the necessary runtime?

**Comment by smaillet-ms** [comment]
At present we don't isolate the instruction set target particularly cleanly. So it would be modifications to a number of places that assume the ISA. I'm cleaning some of that up as I go but there's no set time frame. I'm assuming you are after an M0 target - Which particular SOC are you after?

**Comment by lt72** [comment]
the largest work items would be:
1) re-write the native portion of the CTX switch
2) create a Processor class with the right set of extensions into the system control registers for the M0 (not the same as M3/4) 
3) change interrupt enable/disable model (M0 has no BASEPRI, only PRIMASK) 

Likely a 3 to 4 weeks effort

**Comment by cw2** [comment]
Thanks for the information. Yes, Cortex-M0, ~~STM32F103 in particular (NUCLEO-F103RB)~~ STM32F072 (NUCLEO-F072RB).

If I understand it correctly, the tasks you mention are for the runtime support?

_Edit: Fixed part numbers_

**Comment by smaillet-ms** [comment]
Yes, Lorenzo's comments apply to the runtime (particularly the threading implementation) My comments were in regards to the compilation tools and code generation. 

Are you sure of those part numbers? The [STM32F103](http://www.st.com/web/catalog/mmc/FM141/SC1169/SS1031/LN1565) has a Cortex-M3 in it, which wouldn't require any changes to the code, though the RB variant might be a bit tight on memory right now as we haven't applied a lot of optimizations yet. (We are looking at various levels of optimization now so you should see continued improvement on that over time).

**Comment by cw2** [comment]
Sorry, wrong board - the correct one is NUCLEO-F072RB, which has [STM32F072RB](http://www.st.com/web/catalog/mmc/FM141/SC1169/SS1574/LN1823/PF259605) Cortex-M0.

**Comment by cw2** [comment]
Fixed by 29348c02d8ae1d577e900951bb43441f666cfe32
