### ISSUE TITLE
Few thousands error if checked Native when compile Zelig

### ISSUE THREAD

**Issue by Palomino34** [NETMF/llilum#92]
Hi,
Every time I check Native in Configuration Manager (as picture below), I have few thousands errors below when I compile Zelig.  
Can you please show where I am missing, please?
![llilum_native_build_error](https://cloud.githubusercontent.com/assets/15822304/11698500/df2c00fa-9e8c-11e5-98c9-43022d724db2.jpg)

**Comment by kail** [comment]
Hi,  
Do you have the SDK installed? If not, please follow the steps here: https://github.com/NETMF/llilum/wiki/SDK-User-Guide  

If you have it installed, try clicking "Build" a few times, and see if the number of errors goes down (Visual Studio has issues with unclean directories at times).

Worst case, please use the SDK for all of your development, or follow the steps for using the makefile here (if you are modifying the Llilum compiler or Kernel): https://github.com/NETMF/llilum/wiki/demo

Let us know if you have any more questions!
